# Generated by Django 4.0.6 on 2022-08-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email_alter_user_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='css',
            field=models.TextField(default='check'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='html',
            field=models.TextField(default='check'),
            preserve_default=False,
        ),
    ]
