# Generated by Django 4.1 on 2022-08-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-date_created'], 'verbose_name_plural': 'Contacts'},
        ),
    ]
